language: java
install: ./gradlew setupDevWorkspace eclipse
script: ./gradlew build
cache:
  directories:
  - $HOME/.gradle
  - $HOME/.m2
deploy:
  provider: releases
  api_key:
    secure: j4t1TcDxr5/VbDLnpHntf4Ctgv1M04dC15kJv4hb4TO490kT2Dcu/hSdbY2ktmVUpCzXmiGuHt8g+I75yX3QWCzZyonlFZOUrH6lGf2MazQ+TzA7O4IqR+y6qSjS+5p8Z6IKixRgxEtLE9pBnDjY4yq7R+FiP+PXscnyyWQx9cspDJFK6ml+KJqZ7QHgw4XyMB514UCaEvtgEUObU3xcXCMKvrvmJsbAGXNVb9T2cZSDrRq5MhaXbHXG9T1WIIqsQh+hSTPGpy7YJShV3Zis4S77M+pjeFPXOZcgVCxAf7uqikjlbN6hMstjHNDvwT55dhatK09dIl1M6ivtD1rwiN1zpy/jXyu785fkVgfsqb877JwlaeuOTUaOpQ6mYDydVtVAnY01wB3I+GhylooStxWi7RCPU5Vj8Hmk9hmXB/mOX4RcXKRFBg9a5wyq4kshPsNi5W64UknQ5Q1YkYDjRvNKjpkCKxAQWbhHlEEpJaqbK9EIvpoHI/gW0bxTUhpuLSoLafSsWNZxB8W/UVRR86TIqdhnIAp7fWyn1Gh4BIWun3AdK+3RUiWxM8viZdnaz6mnYQX7cIYicuFSRJ4383DF9ZSt73N1AtjmNLufBr6QKPnMUpVHYTo9dHxO7YKnL+e7mLFp4mhRCwL7YOD/oXk114dlTzQjxv069TWA8nI=
  file: build/libs/InfluenceMod-*.jar
  file_glob: true
  on:
    tags: true
